name: flutter_pos_digital
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Market4u
      fonts:
        - asset: lib/assets/fonts/Market4u.ttf
    - family: Sarabun
      fonts:
        - asset: lib/assets/fonts/sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/sarabun/Sarabun-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: lib/assets/fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/sarabun/Sarabun-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: lib/assets/fonts/sarabun/Sarabun-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/sarabun/Sarabun-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/sarabun/Sarabun-Italic.ttf
          style: italic
          weight: 400
        - asset: lib/assets/fonts/sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/sarabun/Sarabun-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/sarabun/Sarabun-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/sarabun/Sarabun-ExtraBoldItalic.ttf
          style: italic
          weight: 800
    - family: Lexend
      fonts:
        - asset: lib/assets/fonts/lexend/Lexend-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/lexend/Lexend-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/lexend/Lexend-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/lexend/Lexend-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/lexend/Lexend-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/lexend/Lexend-ExtraBold.ttf
          weight: 800
    - family: LexendExa
      fonts:
        - asset: lib/assets/fonts/lexend_exa/LexendExa-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/lexend_exa/LexendExa-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/lexend_exa/LexendExa-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/lexend_exa/LexendExa-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/lexend_exa/LexendExa-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/lexend_exa/LexendExa-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/lexend_exa/LexendExa-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/lexend_exa/LexendExa-ExtraBold.ttf
          weight: 800
    - family: LexendGiga
      fonts:
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/lexend_giga/LexendGiga-ExtraBold.ttf
          weight: 800
